Hw04 auth
vomarchuk/nodejs-homework-REST-API pull request #4
Opened 2021-11-16 21:15 UTC by vomarchuk

look please

2021-11-20 18:25 UTC, KirillKulakow commented on controllers/auth/currentUser.js
> +  console.log(email)
первую строку и консоль можно удалить

2021-11-20 18:26 UTC, KirillKulakow commented on controllers/auth/singin.js
> +const singin = async (req, res, next) => {
в названии метода чуть промахнулся

2021-11-20 18:27 UTC, KirillKulakow commented on controllers/auth/singout.js
> +const singout = async (req, res) => {
в названии метода чуть промахнулся

2021-11-20 18:28 UTC, KirillKulakow commented on controllers/auth/singup.js
> +const singup = async (req, res, next) => {
в названии метода чуть промахнулся, sign

2021-11-20 18:30 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +  const { page, limit = 20 } = req.query
лучше здесь сделать проверку входящего параметра на число - если не число, выдать badRequest
имей ввиду что все что приходит через query это строка

2021-11-20 18:32 UTC, KirillKulakow commented on middleware/authenticate.js
> +    const [bearer, token] = await req.headers.authorization.split(' ')
если я сделаю запрос на список контактов будучи не залогиненым - сломается приложение
ошибка в данной строке

2021-11-20 18:34 UTC, KirillKulakow commented on routes/api/contacts.js
>  router.patch(
мммм... насколько я помню тз то по обновлению контакта используется метод put

2021-11-20 18:35 UTC, KirillKulakow requested changes
Need some fixes

2021-11-21 12:46 UTC, vomarchuk commented on controllers/auth/currentUser.js
> +  console.log(email)
fixed

2021-11-21 12:48 UTC, vomarchuk commented on controllers/auth/singin.js
> +const singin = async (req, res, next) => {
fixed

2021-11-21 12:48 UTC, vomarchuk commented on controllers/auth/singout.js
> +const singout = async (req, res) => {
fixed

2021-11-21 12:50 UTC, vomarchuk commented on controllers/auth/singup.js
> +const singup = async (req, res, next) => {
corrected

2021-11-21 13:33 UTC, vomarchuk commented on controllers/contacts/getAll.js
> +  const { page, limit = 20 } = req.query
corrected but look please my code

2021-11-21 13:48 UTC, vomarchuk commented on middleware/authenticate.js
> +    const [bearer, token] = await req.headers.authorization.split(' ')
corrected

2021-11-21 13:59 UTC, vomarchuk commented on routes/api/contacts.js
>  router.patch(
corrected

2021-11-21 21:24 UTC, KirillKulakow approved these changes

2021-11-22 15:16 UTC, merged