add update  user avatar
vomarchuk/nodejs-homework-REST-API pull request #5
Opened 2021-11-23 19:16 UTC by vomarchuk

please see my code 8)

2021-11-24 20:00 UTC, KirillKulakow commented on controllers/auth/signup.js
> +  const avatarURL = gravatar.url(email)
добавь опцию протокола - для корректной ссылки на аватар

2021-11-24 20:02 UTC, KirillKulakow commented on middleware/upload.js
> +  filename: (req, file, cb) => {
добавь еще проверку на MIME тип файла чтобы кроме картинок ничего другого не загрузить

2021-11-24 20:02 UTC, KirillKulakow requested changes
need some fix

2021-11-24 20:59 UTC, vomarchuk commented on middleware/upload.js
> +  filename: (req, file, cb) => {
added

2021-11-25 14:44 UTC, vomarchuk commented on controllers/auth/signup.js
> +  const avatarURL = gravatar.url(email)
added

2021-11-25 20:03 UTC, KirillKulakow approved these changes

2021-11-25 21:41 UTC, merged