added verification user
vomarchuk/nodejs-homework-REST-API pull request #6
Opened 2021-11-27 19:59 UTC by vomarchuk

I did my best    🤓

2021-11-28 21:55 UTC, KirillKulakow commented on controllers/auth/signin.js
> +  if (!user || !user.verify || !user.comparePassword(password)) {
здесь нужно разделить ошибки, некорректно юзеру писать что у него неправильный пралоь или имейл при том что он не перешел по ссылке в почте(

2021-11-28 21:56 UTC, KirillKulakow requested changes
Need fix

2021-11-28 23:03 UTC, vomarchuk commented on controllers/auth/signin.js
> +  if (!user || !user.verify || !user.comparePassword(password)) {
corrected

2021-11-29 22:32 UTC, KirillKulakow approved these changes

2021-11-29 22:39 UTC, merged